### ISSUE TITLE
Example from blog missing. 

### ISSUE THREAD

**Issue by okouyad** [wi101/zio-examples#20]
In your blog post **ZIO with http4s and doobie**

There was a very good example to understand the module pattern.

> Checkout the code with this approach here. In this section I wanted to go with a simple approach, there is a tip section bellow explains a better way to implement Configuration dependency.

The link at "here is broken."

I wonder if you still have that code somewhere. I did saw it, and the code really helped me understand the subject. I'm revisiting right now, and was hopping to check out that code again.

**Comment by wi101** [comment]
Thanks for reporting that! I wasn't aware that I have removed the branch.
Now it should work :) 
https://github.com/wi101/zio-examples/blob/wz/using-zio-rc18/src/main/scala/com/zio/examples/http4s_doobie/configuration/Configuration.scala

**Comment by okouyad** [comment]
Thank you
