### ISSUE TITLE
Update the article describing the http4s-ZIO-Doobie project

### ISSUE THREAD

**Issue by christophknabe** [wi101/zio-examples#5]
I would kindly request to update the article about this project. With the upgrade of this project to RC18 of ZIO 1.0.0 much of the configuration code in the [excellent Medium article](https://medium.com/@wiemzin/zio-with-http4s-and-doobie-952fba51d089) is no longer valid. So I have difficulties to understand the article and the project. It would be nice to have the article be part of this project as a Markdown file.

**Comment by wi101** [comment]
Thanks 🙏 Yesterday I upgraded it with the latest ZIO version `RC18-2`  and I will update the readme
Thanks for your feedback!

**Comment by christophknabe** [comment]
Hi Wiem,
thanks for your project and article. In fact the ZIO version number `RC18-2` was not the problem for me, but the code in the article did no longer equal to the code in the project.
For example in the article you wrote `case class AppConfig`, in the project this class is named `Config`. In the article there is an
`object Config {
  trait Service {
    val load: Task[AppConfig]
  }
}`, whereas in the project the trait `Service` is in `package object configuration`.
That is why I proposed to have the current version of the article in the same project as a Markdown file. Then I could proof-read it completely, check each code piece and submit a pull request with the necessary modifications for the article.

**Comment by wi101** [comment]
Hi Christoph,
I renamed the `AppConfig` and I added a tip at the blog where I explained the current implementation:
``` scala
  val apiConfig: ZIO[Has[ApiConfig], Throwable, ApiConfig] = ZIO.access(_.get)
  val dbConfig: ZIO[Has[DbConfig], Throwable, DbConfig] = ZIO.access(_.get)
```
in the Markdown I wrote a small summary in #6 and linked each service, please take a look and let me know if I should add specific detail, 
I preferred not to put the whole content of the blog post but I added the link at the end.

**Comment by wi101** [comment]
I pushed the new changes, feel free to open a new PR and suggest changes
Thanks for your feedback!

**Comment by christophknabe** [comment]
Hi Wiem,
thanks for trying to get the article up-to-date. By your encouragement I compiled a complete list of deviations between the article and the current project in my fork in file https://github.com/ChristophKnabe/zio-examples/blob/master/errata.md
I hope you can find the time to update the article. But if some text in the article is only didactic material without direct correspondence to the project code, I would appreciate having it marked very explicitly.

**Comment by wi101** [comment]
Thanks Christoph! I will do that soon

**Comment by wi101** [comment]
Hello Christoph

- For the `Configuration` I refactored the blog post to make it similar than the old implementation in the branch: 
The master branch's implementation it uses different approach that I have explain it at the end of the article.
- **2 Database**: the mktransactor returns ` Managed[Throwable, UserPersistenceService] ` which is the same as `ZManaged[Any, Throwable, UserPersistenceService]` I added the return type though to make it clearer as suggested.
and I removed `.orDie`
- the difference between the `UserPersistenceService.live` in the blog post and the code it that I have used the `configuration.loadConfig` to make it consistent to the reader to follow the same approach but later when I communicated the tip with `type Configuration = Has[DbConfig] with Has[ApiConfig]` dependency it will be clear that in the current code in master it was used that way.
- I fixed the return type of `UserPersistenceService.live`: to
     `ZLayer[Configuration, Throwable, Has[UserPersistenceService]]` and I put ` Has[UserPersistenceService]]` in the article to explain it more that we can use it that way or we define a type alias for it.
- I added in the Tip section how to use the new version of Configuration dependency like in the code .
- I renamed `TestUserDB ` to `Test`
- fixed the return type of `delete`
- adjust the api code in the project
- I fixed the AppEnvironment
- About the point:
"So we can use provideSomeLayer[ZEnv] in which you have to specify the dependencies minus ZEnv, in our case Configuration with UserPersistence", but in the code the dependencies provided are ConfigPrd.live and userPersistence.

yes was it wrong? Configuration with UserPersistence =>  ConfigPrd.live ++ userPersistence
should I say and instead?
- for the:"  final exit status computation io.fold(_ => 1, _ => 0)  " I didn't want to put exactly the same thing with the println

Thanks for the feedback, I fixed the blog post and the code

**Comment by christophknabe** [comment]
Hello Wiem,
thanks for adjusting the article and explaining where the deviations were intentional. Especially the link after the section **1. Configuration:** to the [corresponding, introductory implementation](https://github.com/wi101/zio-examples/blob/wz/using-zio-rc18/src/main/scala/com/zio/examples/http4s_doobie/configuration/Configuration.scala) made many issues clear to me.

- About the point:
"So we can use provideSomeLayer[ZEnv] in which you have to specify the dependencies minus ZEnv, in our case Configuration with UserPersistence", but in the code the dependencies provided are ConfigPrd.live and userPersistence.

After your reply I understand it as
"So we can use `provideSomeLayer[ZEnv]` in which you have to specify the dependencies minus `ZEnv`, in our case `ConfigPrd.live` for `Configuration` and `userPersistence` for `UserPersistence`."
May be you should write it like that.

Thanks again and go on with your work,
Christoph
